// <auto-generated />
using System;
using Group4Flight.Models.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group4Flight.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20260503170301_AddReservationsTable")]
    partial class AddReservationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Group4Flight.Models.DomainModels.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirlineId");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            AirlineId = 1,
                            ImageName = "aircanada.png",
                            Name = "Air Canada"
                        },
                        new
                        {
                            AirlineId = 2,
                            ImageName = "westjet.png",
                            Name = "WestJet"
                        },
                        new
                        {
                            AirlineId = 3,
                            ImageName = "porter.png",
                            Name = "Porter Airlines"
                        },
                        new
                        {
                            AirlineId = 4,
                            ImageName = "flair.png",
                            Name = "Flair Airlines"
                        });
                });

            modelBuilder.Entity("Group4Flight.Models.DomainModels.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ArrivalTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("DepartureTime")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Emission")
                        .HasColumnType("REAL");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AircraftType = "Boeing 737",
                            AirlineId = 1,
                            ArrivalTime = 378000000000L,
                            CabinType = "Economy",
                            Date = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = 288000000000L,
                            Emission = 120.5,
                            FlightCode = "AC101",
                            From = "Toronto",
                            Price = 299.99m,
                            To = "Vancouver"
                        },
                        new
                        {
                            FlightId = 2,
                            AircraftType = "Airbus A320",
                            AirlineId = 1,
                            ArrivalTime = 783000000000L,
                            CabinType = "Business",
                            Date = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = 504000000000L,
                            Emission = 140.0,
                            FlightCode = "AC202",
                            From = "Vancouver",
                            Price = 599.99m,
                            To = "Toronto"
                        },
                        new
                        {
                            FlightId = 3,
                            AircraftType = "Boeing 737",
                            AirlineId = 2,
                            ArrivalTime = 477000000000L,
                            CabinType = "Economy",
                            Date = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = 270000000000L,
                            Emission = 115.2,
                            FlightCode = "WJ301",
                            From = "Calgary",
                            Price = 249.99m,
                            To = "Montreal"
                        },
                        new
                        {
                            FlightId = 4,
                            AircraftType = "Boeing 747",
                            AirlineId = 2,
                            ArrivalTime = 702000000000L,
                            CabinType = "Business",
                            Date = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = 576000000000L,
                            Emission = 118.0,
                            FlightCode = "WJ402",
                            From = "Montreal",
                            Price = 479.99m,
                            To = "Calgary"
                        },
                        new
                        {
                            FlightId = 5,
                            AircraftType = "Embraer E190",
                            AirlineId = 3,
                            ArrivalTime = 360000000000L,
                            CabinType = "Economy",
                            Date = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = 324000000000L,
                            Emission = 45.0,
                            FlightCode = "PD501",
                            From = "Toronto",
                            Price = 129.99m,
                            To = "Ottawa"
                        },
                        new
                        {
                            FlightId = 6,
                            AircraftType = "Embraer E190",
                            AirlineId = 3,
                            ArrivalTime = 684000000000L,
                            CabinType = "First Class",
                            Date = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = 648000000000L,
                            Emission = 47.5,
                            FlightCode = "PD602",
                            From = "Ottawa",
                            Price = 279.99m,
                            To = "Toronto"
                        },
                        new
                        {
                            FlightId = 7,
                            AircraftType = "Airbus A320",
                            AirlineId = 4,
                            ArrivalTime = 279000000000L,
                            CabinType = "Economy",
                            Date = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = 216000000000L,
                            Emission = 60.299999999999997,
                            FlightCode = "F7701",
                            From = "Edmonton",
                            Price = 159.99m,
                            To = "Vancouver"
                        },
                        new
                        {
                            FlightId = 8,
                            AircraftType = "Airbus A320",
                            AirlineId = 1,
                            ArrivalTime = 504000000000L,
                            CabinType = "Business",
                            Date = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = 414000000000L,
                            Emission = 88.700000000000003,
                            FlightCode = "AC303",
                            From = "Toronto",
                            Price = 389.99m,
                            To = "Halifax"
                        },
                        new
                        {
                            FlightId = 9,
                            AircraftType = "Boeing 737",
                            AirlineId = 2,
                            ArrivalTime = 792000000000L,
                            CabinType = "Economy",
                            Date = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = 720000000000L,
                            Emission = 58.100000000000001,
                            FlightCode = "WJ503",
                            From = "Vancouver",
                            Price = 139.99m,
                            To = "Edmonton"
                        },
                        new
                        {
                            FlightId = 10,
                            AircraftType = "Airbus A380",
                            AirlineId = 1,
                            ArrivalTime = 360000000000L,
                            CabinType = "First Class",
                            Date = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = 252000000000L,
                            Emission = 150.0,
                            FlightCode = "AC404",
                            From = "Montreal",
                            Price = 899.99m,
                            To = "Vancouver"
                        });
                });

            modelBuilder.Entity("Group4Flight.Models.DomainModels.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ReservationId");

                    b.HasIndex("FlightId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Group4Flight.Models.DomainModels.Flight", b =>
                {
                    b.HasOne("Group4Flight.Models.DomainModels.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Group4Flight.Models.DomainModels.Reservation", b =>
                {
                    b.HasOne("Group4Flight.Models.DomainModels.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Group4Flight.Models.DomainModels.Airline", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
